version: '2'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    #networks:
    #  static-network:
    #    ipv4_address: 10.2.21.110
    container_name: gitlab
    ports:
    - "880:80"
    - "222:22"
    #environment:
    #- GITLAB_OMNIBUS_CONFIG="external_url 'http://gitlab.local:8880'; gitlab_rails['gitlab_shell_ssh_port']=30033;"
