#!/bin/bash
yum update -y
yum install docker -y
systemctl enable docker && service docker restart
wget -O docker-compose.yaml https://raw.githubusercontent.com/ibrolord/dockerfiles/master/gitlab.yaml
sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
docker-compose --version && docker-compose up -d
